---
- name: playbook
  hosts: ec2-44-212-28-79.compute-1.amazonaws.com
  become: yes
  roles:
    #- patch
    #- users
    #- nginx
    #- packages
    #- docker-compose
    #- docker
    - sonarqube
    #- mysql
    #- postgres
    #- mongodb
    