- name: Install Python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: latest
  become: yes
